<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    protected $table = 'activities';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'judul', 'tanggal_mulai', 'tanggal_berakhir','status', 'hak_akses',
    ];

    public function attachment_activities()
    {
        return $this->hasMany('App\AttachmentActivity');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function archives()
    {
        return $this->hasMany('App\Archive');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function user_activities()
    {
        return $this->hasMany('App\UserActivity');
    }

    public function list_to_dos()
    {
        return $this->hasMany('App\ListToDo');
    }

    public function delete()
    {
        foreach ($this->attachment_activities as $attachment_activity)$attachment_activity->delete();
        foreach ($this->comments as $comment) $comment->delete();
        foreach ($this->archives as $archive) $archive->delete();
        foreach ($this->user_activities as $user_activity) $user_activity->delete();
        foreach ($this->list_to_dos as $list_to_do) $list_to_do->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function getDoneListToDo(){
        return ListToDo::where('activity_id', '=', $this->id)
            ->where('status', '=', 'done')
            ->get();
    }

    public function getUndoneListToDo(){
        return ListToDo::where('activity_id', '=', $this->id)
            ->where('status', '=', 'undone')
            ->get();
    }

    public function getPersentageProgress(){
        if (count($this->list_to_dos)==0){
            return 0;
        }
        else{
            return (count($this->getDoneListToDo())/count($this->list_to_dos))*100;
        }
    }
}
