<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ListToDo extends Model
{
    protected $table = 'list_to_dos';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'judul', 'user_id', 'activity_id', 'status',
    ];

    public function activity()
    {
        return $this->belongsTo('App\Activity');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function attachment_list_to_dos()
    {
        return $this->hasMany('App\AttachmentListToDo');
    }

    public function delete()
    {
        foreach ($this->attachment_list_to_dos as $attachment_list_to_do){
            $attachment_list_to_do->delete();
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
