<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $table = 'profiles';
    public $timestamps = false;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'waktu_update',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
